In [1]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
# Yes, there is a difference in the data types.

# list_ is a regular Python list, which is a collection of objects, and the elements inside it will be of str type.
# array_list is a NumPy array, which can have a uniform data type across all its elements.
# Here’s how you can print the data types of both variables:


import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

# Print data types of both variables
print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {array_list.dtype}")

Data type of list_: <class 'list'>
Data type of array_list: <U1


In [2]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

# Data types of each element in list_
print("Data type of each element in list_:")
for item in list_:
    print(f"{item}: {type(item)}")

# Data types of each element in array_list
print("\nData type of each element in array_list:")
for item in array_list:
    print(f"{item}: {type(item)}")

Data type of each element in list_:
1: <class 'str'>
2: <class 'str'>
3: <class 'str'>
4: <class 'str'>
5: <class 'str'>

Data type of each element in array_list:
1: <class 'numpy.str_'>
2: <class 'numpy.str_'>
3: <class 'numpy.str_'>
4: <class 'numpy.str_'>
5: <class 'numpy.str_'>


In [5]:
# Q3. Considering the following changes in the variable, array_list:

# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

# Yes, after setting dtype=int, the data type of elements in array_list will be int, while list_ remains unchanged as a list of strings.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_, dtype = int)

# Data types of each element in list_
print("Data type of each element in list_:")
for item in list_:
    print(f"{item}: {type(item)}")

# Data types of each element in array_list
print("\nData type of each element in array_list:")
for item in array_list:
    print(f"{item}: {type(item)}")

Data type of each element in list_:
1: <class 'str'>
2: <class 'str'>
3: <class 'str'>
4: <class 'str'>
5: <class 'str'>

Data type of each element in array_list:
1: <class 'numpy.int64'>
2: <class 'numpy.int64'>
3: <class 'numpy.int64'>
4: <class 'numpy.int64'>
5: <class 'numpy.int64'>


In [6]:
# Q4. Write a code to find the following characteristics of the variable num_array:
# (i) shape (ii) size


import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object = num_list)

# Find shape and size of num_array
print(f"Shape of num_array: {num_array.shape}")
print(f"Size of num_array: {num_array.size}")

Shape of num_array: (2, 3)
Size of num_array: 6


In [7]:
# Q5. Write a code to create a NumPy array of a 3x3 matrix containing zeros only, using a NumPy array creation function.
# [Hint: The size of the array will be 9, and the shape will be (3, 3).]


import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

print(f"3x3 matrix of zeros:\n{zero_matrix}")

3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Q6. Create an identity matrix of shape (5, 5) using NumPy functions.
# [Hint: An identity matrix is a matrix containing 1s diagonally, and other elements will be 0.]


import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print(f"5x5 Identity Matrix:\n{identity_matrix}")

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
